services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env  # Loads all environment variables from .env file
    environment:
      - NODE_ENV=production  # Optional: override if needed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s